default_config:

demo:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: yaml
      filename: lovelace.yaml

camera:
  - platform: generic
    still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39635270.Jpeg?type=fullsize

  - platform: generic
    still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39635273.Jpeg?type=fullsize
