version: '3.5'
services:
  road-cam-card:
    image: thomasloven/hass-custom-devcontainer:latest
    environment:
      - HASS_USERNAME
      - HASS_PASSWORD
      - LOVELACE_LOCAL_FILES
      - LOVELACE_PLUGINS
    volumes:
      - ./configuration.yaml:/config/configuration.yaml:ro
      - ./lovelace.yaml:/config/lovelace.yaml:ro
      - ./dist:/config/www/workspace
    ports:
      - "5000:8123"
